baseURL = "/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "reveal-hugo"
RelativeURLs = true
CanonifyURLs = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true
